version: 2

build:
  os: ubuntu-22.04
  tools:
    # Python 3.9 is required here since we are using an old version of Sphinx
    python: "3.9"
    nodejs: "16"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py
