version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.7
  node: circleci/node@5.2.0

commands:
  run-lint-python:
    description: "Run Python linting"
    steps:
      - checkout
      - run: pip install djhtml
      - run: djhtml --check --tabwidth 2 readthedocsext/
  run-build:
    description: "Ensure built assets are up to date"
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run:
          name: Ensure built assets are up to date
          command: |
            if [[ `git status readthedocsext/ --porcelain` ]]
            then
              echo "ERROR: assets are out of date. Make sure to run 'npm run build' on your branch."
              git status readthedocsext/ --porcelain
              exit 1
            fi
  run-test:
    description: "Run test suite"
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run: npm ci
      - run: npm test

jobs:
  lint:
    docker:
      - image: "cimg/python:3.11.8"
    steps:
      - node/install:
          node-version: '20.12'
      - run: node --version
      - run: npm ci
      - run: npm run lint
      - run: pip install pre-commit
      - run: pre-commit run --all-files
  build:
    docker:
      - image: "cimg/node:16.14"
    steps:
      - run-build: {}
  test:
    docker:
      - image: "cimg/node:16.14"
    steps:
      - run-test: {}

workflows:
  version: 2
  tests:
    jobs:
      - lint
      - build
      - test
