version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.7

commands:
  run-lint-node:
    description: "Run Node linting"
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
  run-lint-python:
    description: "Run Python linting"
    steps:
      - checkout
      - pip install djhtml
      - run: djhtml --tabwidth 2 readthedocsext/
  run-build:
    description: "Ensure built assets are up to date"
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run:
          name: Ensure built assets are up to date
          command: |
            if [[ `git status readthedocsext/ --porcelain` ]]
            then
              echo "ERROR: assets are out of date. Make sure to run 'npm run build' on your branch."
              git status readthedocsext/ --porcelain
              exit 1
            fi
  run-test:
    description: "Run test suite"
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run: npm ci
      - run: npm test

jobs:
  lint-node:
    docker:
      - image: "cimg/node:16.14"
    steps:
      - run-lint-node: {}
  lint-python:
    docker:
      - image: "cimg/python:3.11.8"
    steps:
      - run-lint-python: {}
  build:
    docker:
      - image: "cimg/node:16.14"
    steps:
      - run-build: {}
  test:
    docker:
      - image: "cimg/node:16.14"
    steps:
      - run-test: {}

workflows:
  version: 2
  tests:
    jobs:
      - lint-node
      - lint-python
      - build
      - test
